#!/usr/bin/env python


import csv
import datetime
import pandas as pd

from decimal import *
TWOPLACES=Decimal(10) ** -2

headers_a= ['Period','Start Date','Variable','Spend','Product Solution','Market Segment','Geo']

out = open('D:\Adobe\Files from Client\Archive\Media\Display Brand\Example_fair_share.csv', 'wb')
writer = csv.writer(out)
writer.writerow(headers_a)

with open('D:\Adobe\Files from Client\Archive\Media\Display Brand\Example.csv','rU') as inp:
        reader = csv.reader(inp, delimiter=',', quoting=csv.QUOTE_NONE)
        next(reader)
        for column in reader:
            Period = (column[0])
            Start_Date = (column[1])
            Variable = ((column[3]))
            Spend = ((column[5]))
            Product_solution = ((column[2]))
            writer.writerow((Period,Start_Date,Variable,float(Spend) * 0.2,Product_solution,'Education','UK'))
            writer.writerow((Period,Start_Date,Variable,float(Spend) * 0.8,Product_solution,'Non Education','UK'))
out.close()
inp.close()


a = pd.read_csv('D:\Adobe\Files from Client\Archive\Media\Display Brand\Example_fair_share.csv')
grouped = a.groupby(['Period','Start Date','Geo','Market Segment','Variable'],as_index=False).sum()
grouped.to_csv("D:\Adobe\Files from Client\Archive\Media\Display Brand\Example_fair_share_agg",index=False)
